"""Controlled vocabularies shared across the pipeline.

Keeping preferences and activity categories on the *same* enum is deliberate: preference
matching then becomes exact set arithmetic instead of fuzzy string comparison, which keeps
that part of the ranking deterministic and testable.
"""

from enum import StrEnum


class Preference(StrEnum):
    """User interests, also used to tag activities."""

    FOOD = "food"
    CULTURE = "culture"
    NATURE = "nature"
    HISTORY = "history"
    ART = "art"
    NIGHTLIFE = "nightlife"
    SHOPPING = "shopping"
    RELAXATION = "relaxation"


class Currency(StrEnum):
    EUR = "EUR"


class Provenance(StrEnum):
    """Where a piece of information came from.

    Every fact surfaced to the user carries one of these. It is what lets the UI tell
    retrieved facts apart from synthetic fixtures and model prose.
    """

    REAL_API = "real_api"
    """Retrieved live from a third-party provider during this request."""

    SNAPSHOT = "snapshot"
    """Real provider data captured once and frozen as a versioned fixture."""

    SYNTHETIC = "synthetic"
    """Generated by us. Never to be presented as a real-world fact."""

    MODEL_GENERATED = "model_generated"
    """Free text produced by the LLM, grounded in the records above."""


class BudgetCategory(StrEnum):
    ACCOMMODATION = "accommodation"
    ACTIVITIES = "activities"
    FOOD = "food"
    TRANSPORT = "transport"


class Severity(StrEnum):
    """Hard constraints block a recommendation; soft ones only warn."""

    HARD = "hard"
    SOFT = "soft"
